#!/usr/bin/env bash

recipe_file="$1"
branch_name="$2"

build_dir="/home/${recipe_file}-${branch_name}"

sudo singularity exec --bind "$PWD":"/home" --writable "$1" /home/install_Sherpa "$build_dir" "$branch_name"
