#!/usr/bin/env bash

if [ -z ${BLACKHAT_PREFIX+x} ] ; then
	echo 'ERROR: $BLACKHAT_PREFIX is unset'
	exit 1
fi

# the directory of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# the temp directory used, within $DIR
# omit the -p parameter to create a temporal directory in the default location
WORK_DIR=`mktemp -d -p "$DIR"`

# check if tmp dir was created
if [[ ! "$WORK_DIR" || ! -d "$WORK_DIR" ]]; then
	echo "Could not create temp dir"
	exit 1
fi

# deletes the temp directory
function cleanup {
	rm -rf "$WORK_DIR"
	echo "Deleted temp working directory $WORK_DIR"
}

# register the cleanup function to be called on the EXIT signal
trap cleanup EXIT

cd "$WORK_DIR"

echo Installing QD library
wget http://crd.lbl.gov/~dhbailey/mpdist/qd-2.3.22.tar.gz -O- | tar xz
cd qd-2.3.22
./configure --prefix="$BLACKHAT_PREFIX" --enable-shared
make -j && make install
cd -

echo Installing BlackHat
wget https://www.theorie.physik.uni-goettingen.de/~bothmann/blackhat-r3095_source.tar.gz -O- | tar xz
cd blackhat-r3095
./configure --with-QDpath="$BLACKHAT_PREFIX" --prefix="$BLACKHAT_PREFIX" --enable-public=no --enable-readline=no CXXFLAGS="-Wno-deprecated"
# NOTE: BlackHat has issues when using parallel build jobs
make -j1 && make install
