#!/usr/bin/env bash

# NOTE: OpenLoops 1.3.1 or later needs gfortran 4.6 or newer

version=${1:-2.0.0}

echo Installing OpenLoops
wget https://openloops.hepforge.org/downloads?f=OpenLoops-$version.tar.gz -O- | tar xz
cd OpenLoops-$version/
./scons
