#!/usr/bin/env bash

# NOTE: OpenLoops 1.3.1 or later needs gfortran 4.6 or newer

version=${1:-2.1.1}

echo Installing OpenLoops
wget https://openloops.hepforge.org/downloads?f=OpenLoops-$version.tar.gz -O- | tar xz
cd OpenLoops-$version/
./scons

patch -p1 lib_src/openloops/src/kinematics.F90 - <<<"1121c1121
<   P_in(:,n_scatt+1:)  = - scalefactor * P_ex(:,n_scatt+1:)
---
>   P_in(:,n_scatt+1:n)  = - scalefactor * P_ex(:,n_scatt+1:n)
"

./scons
